branch-defaults:
  default:
    environment: Flasky1-env
  smtp_qq:
    environment: Flasky1-env
environment-defaults:
  Flasky1-env:
    branch: null
    repository: null
global:
  application_name: flasky1
  branch: null
  default_ec2_keyname: awshongkong1
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: ap-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
